### ISSUE TITLE
PowerPoint OBS Add-In

### ISSUE THREAD

**Issue by Alyss-Swanson** [tvanyo/obsPPTXwithPython#1]
Todd, I hope that this message finds you well.

Like you, I have been searching for a way to replicate the PowerPoint-OBS work by Scott Hanselman, and especially on the Mac. I notice that you have been able to do that although it's not clear to me how I might take what you've done and make it an executable app.  I would welcome the opportunity to speak with you (alyss.swanson@gmail.com) at your convenience so that I might learn more.  Perhaps at the same time, I might be able to share how I might imagine this idea might be advanced any further.  Thanks. -Alyss

**Comment by tvanyo** [comment]
@Alyss-Swanson, there are multiple ways to turn a python script into an executable. A quick [search on stackoverflow](https://stackoverflow.com/search?q=turn+python+script+into+executable) returns over 300 items; Pyinstaller and py2exe are the most common (and appear at the top).

That said, it is beyond the scope of what I was trying to do with this to turn it into an executable. Most of it would be straight forward, I'm not sure if that is "easy" or not with pygame. Probably is, as plenty of people have apparently done it. It's been a couple of years since I created a standalone executable, as running things out of terminal is just as easy IMO.

If you need help getting a newer version python, I can help you get what is needed setup on your machine. 

It might make sense to split the file into Start, Advance, and Retreat scripts. Then an app like Keysmith or Alfred could be used to launch the appropriate script based on key press. I will make those changes and post an update in the next week or so.

**Comment by Alyss-Swanson** [comment]
Todd,

	Thank you so very much for the quick reply. Since writing to you I’ve had the opportunity to learn a fair amount more about Python, which Ive never personally programmed in before; I’m a C/C++ programmer that has done considerable embedded microcontroller programming sometime ago.  Since then I did a hard right turn, going back to grad school and seminary to now work as a Pastoral Pschotherapist.  That said, I’m now supporting my church doing live-streaming which has been another huge learning experience.  I now realize that Python is an interpretive scripting language.  It looks as if I should be able to easily call it from the PowerPoint VBA macro that I’m actively creating.  Unlike what you’ve done, I’m approaching the problem from a framework where PowerPoint works as it normally does and at the same time a macro event handler is called every time a slide is changed.  When a slide is changed, it will call the Python OBS script while passing the scene name to it. 

Regards,
-Alyss
